/** Country-name → demonym mapping for nationality dropdown */
export const NATIONALITIES: { country: string; nationality: string }[] = [
  { country: "Afghanistan", nationality: "Afghan" },
  { country: "Albania", nationality: "Albanian" },
  { country: "Algeria", nationality: "Algerian" },
  { country: "Andorra", nationality: "Andorran" },
  { country: "Angola", nationality: "Angolan" },
  { country: "Argentina", nationality: "Argentine" },
  { country: "Armenia", nationality: "Armenian" },
  { country: "Australia", nationality: "Australian" },
  { country: "Austria", nationality: "Austrian" },
  { country: "Azerbaijan", nationality: "Azerbaijani" },
  { country: "Bahamas", nationality: "Bahamian" },
  { country: "Bahrain", nationality: "Bahraini" },
  { country: "Bangladesh", nationality: "Bangladeshi" },
  { country: "Barbados", nationality: "Barbadian" },
  { country: "Belarus", nationality: "Belarusian" },
  { country: "Belgium", nationality: "Belgian" },
  { country: "Belize", nationality: "Belizean" },
  { country: "Benin", nationality: "Beninese" },
  { country: "Bhutan", nationality: "Bhutanese" },
  { country: "Bolivia", nationality: "Bolivian" },
  { country: "Bosnia and Herzegovina", nationality: "Bosnian" },
  { country: "Botswana", nationality: "Motswana" },
  { country: "Brazil", nationality: "Brazilian" },
  { country: "Brunei", nationality: "Bruneian" },
  { country: "Bulgaria", nationality: "Bulgarian" },
  { country: "Burkina Faso", nationality: "Burkinabé" },
  { country: "Burundi", nationality: "Burundian" },
  { country: "Cambodia", nationality: "Cambodian" },
  { country: "Cameroon", nationality: "Cameroonian" },
  { country: "Canada", nationality: "Canadian" },
  { country: "Cape Verde", nationality: "Cape Verdean" },
  { country: "Central African Republic", nationality: "Central African" },
  { country: "Chad", nationality: "Chadian" },
  { country: "Chile", nationality: "Chilean" },
  { country: "China", nationality: "Chinese" },
  { country: "Colombia", nationality: "Colombian" },
  { country: "Comoros", nationality: "Comorian" },
  { country: "Congo", nationality: "Congolese" },
  { country: "Costa Rica", nationality: "Costa Rican" },
  { country: "Croatia", nationality: "Croatian" },
  { country: "Cuba", nationality: "Cuban" },
  { country: "Cyprus", nationality: "Cypriot" },
  { country: "Czech Republic", nationality: "Czech" },
  { country: "Denmark", nationality: "Danish" },
  { country: "Djibouti", nationality: "Djiboutian" },
  { country: "Dominican Republic", nationality: "Dominican" },
  { country: "Ecuador", nationality: "Ecuadorian" },
  { country: "Egypt", nationality: "Egyptian" },
  { country: "El Salvador", nationality: "Salvadoran" },
  { country: "Equatorial Guinea", nationality: "Equatoguinean" },
  { country: "Eritrea", nationality: "Eritrean" },
  { country: "Estonia", nationality: "Estonian" },
  { country: "Eswatini", nationality: "Swazi" },
  { country: "Ethiopia", nationality: "Ethiopian" },
  { country: "Fiji", nationality: "Fijian" },
  { country: "Finland", nationality: "Finnish" },
  { country: "France", nationality: "French" },
  { country: "Gabon", nationality: "Gabonese" },
  { country: "Gambia", nationality: "Gambian" },
  { country: "Georgia", nationality: "Georgian" },
  { country: "Germany", nationality: "German" },
  { country: "Ghana", nationality: "Ghanaian" },
  { country: "Greece", nationality: "Greek" },
  { country: "Guatemala", nationality: "Guatemalan" },
  { country: "Guinea", nationality: "Guinean" },
  { country: "Guyana", nationality: "Guyanese" },
  { country: "Haiti", nationality: "Haitian" },
  { country: "Honduras", nationality: "Honduran" },
  { country: "Hungary", nationality: "Hungarian" },
  { country: "Iceland", nationality: "Icelandic" },
  { country: "India", nationality: "Indian" },
  { country: "Indonesia", nationality: "Indonesian" },
  { country: "Iran", nationality: "Iranian" },
  { country: "Iraq", nationality: "Iraqi" },
  { country: "Ireland", nationality: "Irish" },
  { country: "Israel", nationality: "Israeli" },
  { country: "Italy", nationality: "Italian" },
  { country: "Ivory Coast", nationality: "Ivorian" },
  { country: "Jamaica", nationality: "Jamaican" },
  { country: "Japan", nationality: "Japanese" },
  { country: "Jordan", nationality: "Jordanian" },
  { country: "Kazakhstan", nationality: "Kazakh" },
  { country: "Kenya", nationality: "Kenyan" },
  { country: "Kuwait", nationality: "Kuwaiti" },
  { country: "Kyrgyzstan", nationality: "Kyrgyz" },
  { country: "Laos", nationality: "Laotian" },
  { country: "Latvia", nationality: "Latvian" },
  { country: "Lebanon", nationality: "Lebanese" },
  { country: "Lesotho", nationality: "Mosotho" },
  { country: "Liberia", nationality: "Liberian" },
  { country: "Libya", nationality: "Libyan" },
  { country: "Liechtenstein", nationality: "Liechtensteiner" },
  { country: "Lithuania", nationality: "Lithuanian" },
  { country: "Luxembourg", nationality: "Luxembourgish" },
  { country: "Madagascar", nationality: "Malagasy" },
  { country: "Malawi", nationality: "Malawian" },
  { country: "Malaysia", nationality: "Malaysian" },
  { country: "Maldives", nationality: "Maldivian" },
  { country: "Mali", nationality: "Malian" },
  { country: "Malta", nationality: "Maltese" },
  { country: "Mauritania", nationality: "Mauritanian" },
  { country: "Mauritius", nationality: "Mauritian" },
  { country: "Mexico", nationality: "Mexican" },
  { country: "Moldova", nationality: "Moldovan" },
  { country: "Monaco", nationality: "Monégasque" },
  { country: "Mongolia", nationality: "Mongolian" },
  { country: "Montenegro", nationality: "Montenegrin" },
  { country: "Morocco", nationality: "Moroccan" },
  { country: "Mozambique", nationality: "Mozambican" },
  { country: "Myanmar", nationality: "Burmese" },
  { country: "Namibia", nationality: "Namibian" },
  { country: "Nepal", nationality: "Nepali" },
  { country: "Netherlands", nationality: "Dutch" },
  { country: "New Zealand", nationality: "New Zealander" },
  { country: "Nicaragua", nationality: "Nicaraguan" },
  { country: "Niger", nationality: "Nigerien" },
  { country: "Nigeria", nationality: "Nigerian" },
  { country: "North Korea", nationality: "North Korean" },
  { country: "North Macedonia", nationality: "Macedonian" },
  { country: "Norway", nationality: "Norwegian" },
  { country: "Oman", nationality: "Omani" },
  { country: "Pakistan", nationality: "Pakistani" },
  { country: "Palestine", nationality: "Palestinian" },
  { country: "Panama", nationality: "Panamanian" },
  { country: "Papua New Guinea", nationality: "Papua New Guinean" },
  { country: "Paraguay", nationality: "Paraguayan" },
  { country: "Peru", nationality: "Peruvian" },
  { country: "Philippines", nationality: "Filipino" },
  { country: "Poland", nationality: "Polish" },
  { country: "Portugal", nationality: "Portuguese" },
  { country: "Qatar", nationality: "Qatari" },
  { country: "Romania", nationality: "Romanian" },
  { country: "Russia", nationality: "Russian" },
  { country: "Rwanda", nationality: "Rwandan" },
  { country: "Saudi Arabia", nationality: "Saudi" },
  { country: "Senegal", nationality: "Senegalese" },
  { country: "Serbia", nationality: "Serbian" },
  { country: "Sierra Leone", nationality: "Sierra Leonean" },
  { country: "Singapore", nationality: "Singaporean" },
  { country: "Slovakia", nationality: "Slovak" },
  { country: "Slovenia", nationality: "Slovenian" },
  { country: "Somalia", nationality: "Somali" },
  { country: "South Africa", nationality: "South African" },
  { country: "South Korea", nationality: "South Korean" },
  { country: "South Sudan", nationality: "South Sudanese" },
  { country: "Spain", nationality: "Spanish" },
  { country: "Sri Lanka", nationality: "Sri Lankan" },
  { country: "Sudan", nationality: "Sudanese" },
  { country: "Suriname", nationality: "Surinamese" },
  { country: "Sweden", nationality: "Swedish" },
  { country: "Switzerland", nationality: "Swiss" },
  { country: "Syria", nationality: "Syrian" },
  { country: "Taiwan", nationality: "Taiwanese" },
  { country: "Tajikistan", nationality: "Tajik" },
  { country: "Tanzania", nationality: "Tanzanian" },
  { country: "Thailand", nationality: "Thai" },
  { country: "Togo", nationality: "Togolese" },
  { country: "Trinidad and Tobago", nationality: "Trinidadian" },
  { country: "Tunisia", nationality: "Tunisian" },
  { country: "Turkey", nationality: "Turkish" },
  { country: "Turkmenistan", nationality: "Turkmen" },
  { country: "Uganda", nationality: "Ugandan" },
  { country: "Ukraine", nationality: "Ukrainian" },
  { country: "United Arab Emirates", nationality: "Emirati" },
  { country: "United Kingdom", nationality: "British" },
  { country: "United States", nationality: "American" },
  { country: "Uruguay", nationality: "Uruguayan" },
  { country: "Uzbekistan", nationality: "Uzbek" },
  { country: "Venezuela", nationality: "Venezuelan" },
  { country: "Vietnam", nationality: "Vietnamese" },
  { country: "Yemen", nationality: "Yemeni" },
  { country: "Zambia", nationality: "Zambian" },
  { country: "Zimbabwe", nationality: "Zimbabwean" },
];

/** Priority nationalities shown at top of dropdown */
export const PRIORITY_NATIONALITIES = ["Swedish", "Romanian", "Thai", "Ukrainian"];

/** Get ordered nationality list with priority items first */
export function getOrderedNationalities() {
  const priority = NATIONALITIES.filter((n) => PRIORITY_NATIONALITIES.includes(n.nationality));
  const rest = NATIONALITIES.filter((n) => !PRIORITY_NATIONALITIES.includes(n.nationality));
  return { priority, rest };
}
