project_id = "nssppfuaxhijqbmsquhd"

[functions.send-signing-email]
verify_jwt = false

[functions.lookup-company]
verify_jwt = false

[functions.validate-address]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.validate-onboarding-fields]
verify_jwt = false

[functions.send-role-notification]
verify_jwt = false

[functions.check-pending-role]
verify_jwt = false

[functions.cleanup-orphan-user]
verify_jwt = false